---
models:
  granite:
    ollama_model: granite4:32b-a9b-h
  glm:
    ollama_model: glm-4.7-flash
  gemma:
    ollama_model: gemma4:26b
  qwen:
    ollama_model: qwen3.6:35b-a3b
  nemotron:
    ollama_model: nemotron-3-nano:30b
  gptoss:
    ollama_model: gpt-oss:20b
  gemma4mlx:
    ollama_model: gemma4:31b-mlx
  ministral:
    ollama_model: ministral-3:14b-instruct-2512-q4_K_M
